# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/AndrewSamokhvalov/slice"

[[constraint]]
  branch = "master"
  name = "github.com/bitlum/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/bitlum/btcutil"

[[constraint]]
  name = "github.com/coreos/bbolt"
  revision = "4f5275f4ebbf6fe7cb772de987fa96ee674460a7"

[[constraint]]
  name = "github.com/btcsuite/btclog"
  revision = "84c8d2346e9fc8c7b947e243b9c24e6df9fd206a"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-socks"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/websocket"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  revision = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.2"

[[constraint]]
  name = "github.com/go-errors/errors"
  revision = "a6af135bd4e28680facf08a3d206b454abc877a4"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "bbd03ef6da3a115852eaf24c8a1c46aeb39aa175"

[[constraint]]
  name = "github.com/jrick/logrotate"
  revision = "a93b200c26cbae3bb09dd0dc2c7c7fe1468a034a"

[[constraint]]
  name = "github.com/lightningnetwork/lnd"
  version = "0.4.1-beta"

[[constraint]]
  name = "github.com/ltcsuite/ltcd"
  revision = "5f654d5faab99ee2b3488fabba98e5f7a5257ee3"

[[constraint]]
  branch = "master"
  name = "github.com/onrik/ethrpc"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/schancel/cashaddr-converter"
  version = "9.0.0"

[[constraint]]
  name = "github.com/shopspring/decimal"
  version = "1.0.1"

[[constraint]]
  name = "golang.org/x/net"
  revision = "ae89d30ce0c63142b652837da33d782e2b0a9b25"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "b3ddf786825de56a4178401b7e174ee332173b66"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true
