version: "3.5"


# Explicitly defined connector network to be able to set static IPs
networks:
  connector.simnet:
    name: connector.simnet
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.1.0/24

# Default settings for all containers.
x-defaults:
  &defaults

  # Using syslog driver and set tag to container_name.
  logging:
    driver: syslog
    options:
      tag: "connector-docker/{{ .Name }}"

  # Using automatically assigned ip address from connect.simnet network.
  networks:
    connector.simnet:

  # Restart on exit.
  restart: always

  # Wait for one minute for gracefull shutdown
  stop_grace_period: 1m



services:

  ######################################################################
  #
  # Environment variables and arguments
  #
  # This arguments and environment variables used across containers.
  #
  # EXTERNAL_IP is server's public IP address available for other
  # nodes or clients to connect and used by daemon to announce
  # right location.
  #
  # PRIVATE_IP is IP address from private network which is not
  # public accessible. It is used by secure subsystems to bind on.
  #
  # ROLE is coins' node role: `primary` or `secondary`.
  # Primary role means that this node will init new blockchain if it not
  # exists during deploy or restart.
  # Secondary rank means that this node will try to connect to primary
  # node and use blockchain of latter.
  #
  ######################################################################


  ######################################################################
  #
  # Single simnet containers
  #
  # This containers are used both by primary and secondary containers
  # and should be started only once.
  #
  ######################################################################

  blocks-generator.simnet:
    << : *defaults
    container_name: blocks-generator.simnet
    image: blocks-generator.simnet
    build:
      context: ./blocks-generator
      args:
        - BITCOIN_VERSION
        - BITCOIN_CASH_VERSION
        - DASH_VERSION
        - LITECOIN_VERSION
    depends_on:
      - bitcoin.simnet.primary
      - bitcoin-cash.simnet.primary
      - dash.simnet.primary
      - litecoin.simnet.primary

  ethereum-bootnode.simnet:
    << : *defaults
    container_name: ethereum-bootnode.simnet
    networks:
      connector.simnet:
        # Make ip static so that enode url written in the enode file has been
        # valid after restarts.
        ipv4_address: 172.100.0.2
    image: ethereum-bootnode.simnet
    build:
      context: ./ethereum-bootnode
      args:
        - ETHEREUM_REVISION
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/ethereum-bootnode.simnet:/bootnode



  ######################################################################
  #
  # Simnet primary containers
  #
  ######################################################################

  connector.simnet.primary:
    << : *defaults
    container_name: connector.simnet.primary
    image: connector.simnet.primary
    build:
      context: ./connector
      args:
        - ROLE=primary
    volumes:
      - /connector/connector.simnet.primary:/root/.connector
      - /connector/bitcoin-lightning.simnet.primary:/root/.lnd/:ro
    ports:
      # RPC port
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:9002:9002"
      # Prometheus monitoring
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:9999:9999"
    depends_on:
      - bitcoin.simnet.primary
      - bitcoin-lightning.simnet.primary
      - bitcoin-cash.simnet.primary
      - dash.simnet.primary
      - ethereum.simnet.primary
      - litecoin.simnet.primary

  bitcoin.simnet.primary:
    << : *defaults
    container_name: bitcoin.simnet.primary
    image: bitcoin.simnet.primary
    build:
      context: ./bitcoin
      args:
        - BITCOIN_VERSION
        - ROLE=primary
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/bitcoin.simnet.primary:/root/.bitcoin

  bitcoin-lightning.simnet.primary:
    << : *defaults
    container_name: bitcoin-lightning.simnet.primary
    image: bitcoin-lightning.simnet.primary
    build:
      context: ./bitcoin-lightning
      args:
        - BITCOIN_LIGHTNING_REVISION
        - ROLE=primary
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/bitcoin.simnet.primary:/root/.bitcoin:ro
      - /connector/bitcoin-lightning.simnet.primary:/root/.lnd
    depends_on:
      - bitcoin.simnet.primary
      - blocks-generator.simnet

  bitcoin-lightning-helper.simnet.primary:
    << : *defaults
    container_name: bitcoin-lightning-helper.simnet.primary
    image: bitcoin-lightning-helper.simnet.primary
    build:
      context: ./bitcoin-lightning-helper
      args:
        - BITCOIN_LIGHTNING_REVISION
    volumes:
      - /connector/bitcoin-lightning.simnet.primary:/root/.lnd/:ro
    ports:
      - "3000:80"
    depends_on:
      - bitcoin-lightning.simnet.primary

  bitcoin-cash.simnet.primary:
    << : *defaults
    container_name: bitcoin-cash.simnet.primary
    image: bitcoin-cash.simnet.primary
    build:
      context: ./bitcoin-cash
      args:
        - BITCOIN_CASH_VERSION
        - ROLE=primary
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/bitcoin-cash.simnet.primary:/root/.bitcoin

  dash.simnet.primary:
    << : *defaults
    container_name: dash.simnet.primary
    image: dash.simnet.primary
    build:
      context: ./dash
      args:
        - DASH_VERSION
        - ROLE=primary
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/dash.simnet.primary:/root/.dashcore

  ethereum.simnet.primary:
    << : *defaults
    container_name: ethereum.simnet.primary
    image: ethereum.simnet.primary
    build:
      context: ./ethereum
      args:
        - ETHEREUM_REVISION
        - ROLE=primary
    environment:
      - EXTERNAL_IP
      # MINE to mine or not, should be 1 or 0.
      - MINE=1
    volumes:
      - /connector/ethereum.simnet.primary:/root/.ethereum
      - /connector/ethereum-bootnode.simnet:/bootnode
    depends_on:
      - ethereum-bootnode.simnet

  litecoin.simnet.primary:
    << : *defaults
    container_name: litecoin.simnet.primary
    image: litecoin.simnet.primary
    build:
      context: ./litecoin
      args:
        - LITECOIN_VERSION
        - ROLE=primary
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/litecoin.simnet.primary:/root/.litecoin



  ######################################################################
  #
  # Simnet secondary containers
  #
  ######################################################################

  connector.simnet.secondary:
    << : *defaults
    container_name: connector.simnet.secondary
    image: connector.simnet.secondary
    build:
      context: ./connector
      args:
        - ROLE=secondary
    volumes:
      - /connector/connector.simnet.secondary:/root/.connector
      - /connector/bitcoin-lightning.simnet.secondary:/root/.lnd/:ro
    ports:
      # RPC port
      - "10000:9003"
      # Prometheus monitoring
      - "9998:9998"
    depends_on:
      - bitcoin.simnet.secondary
      - bitcoin-lightning.simnet.secondary
      - bitcoin-cash.simnet.secondary
      - dash.simnet.secondary
      - ethereum.simnet.secondary
      - litecoin.simnet.secondary

  bitcoin.simnet.secondary:
    << : *defaults
    container_name: bitcoin.simnet.secondary
    image: bitcoin.simnet.secondary
    build:
      context: ./bitcoin
      args:
        - BITCOIN_VERSION
        - ROLE=secondary
    volumes:
      - /connector/bitcoin.simnet.secondary:/root/.bitcoin
    ports:
      - "10001:8332"
    depends_on:
      - bitcoin.simnet.primary

  bitcoin-lightning.simnet.secondary:
    << : *defaults
    container_name: bitcoin-lightning.simnet.secondary
    image: bitcoin-lightning.simnet.secondary
    build:
      context: ./bitcoin-lightning
      args:
        - BITCOIN_LIGHTNING_REVISION
        - ROLE=secondary
    ports:
      - "10002:10009"
    volumes:
      - /connector/bitcoin.simnet.secondary:/root/.bitcoin:ro
      - /connector/bitcoin-lightning.simnet.secondary:/root/.lnd
    depends_on:
      - bitcoin.simnet.secondary
      - blocks-generator.simnet

  bitcoin-lightning.simnet.third:
    << : *defaults
    container_name: bitcoin-lightning.simnet.third
    image: bitcoin-lightning.simnet.secondary
    build:
      context: ./bitcoin-lightning
      args:
        - BITCOIN_LIGHTNING_REVISION
        - ROLE=secondary
    volumes:
      - /connector/bitcoin.simnet.secondary:/root/.bitcoin:ro
      - /connector/bitcoin-lightning.simnet.third:/root/.lnd
    depends_on:
      - bitcoin.simnet.secondary
      - blocks-generator.simnet

  bitcoin-cash.simnet.secondary:
    << : *defaults
    container_name: bitcoin-cash.simnet.secondary
    image: bitcoin-cash.simnet.secondary
    build:
      context: ./bitcoin-cash
      args:
        - BITCOIN_CASH_VERSION
        - ROLE=secondary
    volumes:
      - /connector/bitcoin-cash.simnet.secondary:/root/.bitcoin
    ports:
      - "10003:9332"
    depends_on:
      - bitcoin-cash.simnet.primary

  dash.simnet.secondary:
    << : *defaults
    container_name: dash.simnet.secondary
    image: dash.simnet.secondary
    build:
      context: ./dash
      args:
        - DASH_VERSION
        - ROLE=secondary
    volumes:
      - /connector/dash.simnet.secondary:/root/.dashcore
    ports:
      - "10004:10332"
    depends_on:
      - dash.simnet.primary

  ethereum.simnet.secondary:
    << : *defaults
    container_name: ethereum.simnet.secondary
    image: ethereum.simnet.secondary
    build:
      context: ./ethereum
      args:
        - ETHEREUM_REVISION
        - ROLE=secondary
    environment:
      - MINE=0
      - EXTERNAL_IP
    volumes:
      - /connector/ethereum.simnet.secondary:/root/.ethereum
      - /connector/ethereum-bootnode.simnet:/bootnode
    ports:
      - "10005:11332"
    depends_on:
      - ethereum-bootnode.simnet
      - ethereum.simnet.primary

  litecoin.simnet.secondary:
    << : *defaults
    container_name: litecoin.simnet.secondary
    image: litecoin.simnet.secondary
    build:
      context: ./litecoin
      args:
        - LITECOIN_VERSION
        - ROLE=secondary
    volumes:
      - /connector/litecoin.simnet.secondary:/root/.litecoin
    ports:
      - "10006:12332"
    depends_on:
      - litecoin.simnet.primary
