version: "3.5"

# Explicitly defined connector network to be able to set static IPs
networks:
  connector.testnet:
    name: connector.testnet
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.1.0/24



# Default settings for all containers.
x-defaults:
  &defaults

  # Using automatically assigned ip address from connect.testnet network.
  networks:
    connector.testnet:

  # Using syslog driver and set tag to container_name.
  logging:
    driver: syslog
    options:
      tag: "connector-docker/{{ .Name }}"

  # Restart on exit.
  restart: always



services:

  ######################################################################
  #
  # Environment variables and arguments
  #
  # This arguments and environment variables used across containers.
  #
  # EXTERNAL_IP is server's public IP address available for other
  # nodes or clients to connect and used by daemon to announce
  # right location.
  #
  ######################################################################

  ######################################################################
  #
  # Testnet containers
  #
  # This containers intended to be run on standalone machine. You should
  # create new machine for each deploy.
  #
  ######################################################################

  connector.testnet:
    << : *defaults
    container_name: connector.testnet
    image: connector.testnet
    build:
      context: ./connector/
      args:
        - CONNECTOR_REVISION
    environment:
      - EXCHANGE_DISABLED
      - BITCOIN_RPC_USER
      - BITCOIN_RPC_PASSWORD
      - BITCOIN_CASH_RPC_USER
      - BITCOIN_CASH_RPC_PASSWORD
      - DASH_RPC_USER
      - DASH_RPC_PASSWORD
      - LITECOIN_RPC_USER
      - LITECOIN_RPC_PASSWORD
    networks:
      connector.testnet:
        ipv4_address: 172.100.1.100
    volumes:
      - /connector/connector.testnet:/root/.connector
      - /connector/bitcoin-lightning.testnet:/root/.lnd/:ro
    ports:
      # RPC port
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:9002:9002"
      # Prometheus monitoring
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:9999:9999"
    depends_on:
      - bitcoin.testnet
      - bitcoin-lightning.testnet
      - bitcoin-cash.testnet
      - dash.testnet
      - ethereum.testnet
      - litecoin.testnet

  bitcoin.testnet:
    << : *defaults
    container_name: bitcoin.testnet
    image: bitcoin.testnet
    build:
      context: ./bitcoin
      args:
        - BITCOIN_VERSION
    environment:
      - EXTERNAL_IP
      - BITCOIN_RPC_AUTH
      - BITCOIN_RPC_USER
      - BITCOIN_RPC_PASSWORD
    volumes:
      - /connector/bitcoin.testnet:/root/.bitcoin
    ports:
      # P2P port
      - "8333:8333"

  bitcoin-lightning.testnet:
    << : *defaults
    container_name: bitcoin-lightning.testnet
    image: bitcoin-lightning.testnet
    build:
      context: ./bitcoin-lightning
      args:
        - BITCOIN_LIGHTNING_REVISION
    environment:
      - EXTERNAL_IP
      - BITCOIN_RPC_USER
      - BITCOIN_RPC_PASSWORD
    networks:
      connector.testnet:
        ipv4_address: 172.100.1.101
    volumes:
      - /connector/bitcoin.testnet:/root/.bitcoin:ro
      - /connector/bitcoin-lightning.testnet:/root/.lnd
    ports:
      # P2P port
      - "9735:9735"
    depends_on:
      - bitcoin.testnet

  bitcoin-neutrino.testnet:
    << : *defaults
    container_name: bitcoin-neutrino.testnet
    image: bitcoin-neutrino.testnet
    build:
      context: ./bitcoin-neutrino
      args:
        - BITCOIN_NEUTRINO_REVISION
    environment:
      - EXTERNAL_IP
      - BITCOIN_NEUTRINO_RPC_USER
      - BITCOIN_NEUTRINO_RPC_PASSWORD
    volumes:
      - /connector/bitcoin-neutrino.testnet:/root/.btcd
    ports:
      # RPC port
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:13332:13332"
      # P2P port
      - "13333:13333"

  bitcoin-cash.testnet:
    << : *defaults
    container_name: bitcoin-cash.testnet
    image: bitcoin-cash.testnet
    build:
      context: ./bitcoin-cash
      args:
        - BITCOIN_CASH_VERSION
    environment:
      - EXTERNAL_IP
      - BITCOIN_CASH_RPC_AUTH
      - BITCOIN_CASH_RPC_USER
      - BITCOIN_CASH_RPC_PASSWORD
    volumes:
      - /connector/bitcoin-cash.testnet:/root/.bitcoin
    ports:
      # P2P port
      - "9333:9333"
  
  dash.testnet:
    << : *defaults
    container_name: dash.testnet
    image: dash.testnet
    build:
      context: ./dash
      args:
        - DASH_VERSION
    environment:
      - EXTERNAL_IP
      - DASH_RPC_AUTH
      - DASH_RPC_USER
      - DASH_RPC_PASSWORD
    volumes:
      - /connector/dash.testnet:/root/.dashcore
    ports:
      # P2P port
      - "10333:10333"

  ethereum.testnet:
    << : *defaults
    container_name: ethereum.testnet
    image: ethereum.testnet
    build:
      context: ./ethereum
      args:
        - ETHEREUM_REVISION
    environment:
      - EXTERNAL_IP
    volumes:
      - /connector/ethereum.testnet:/root/.ethereum
    ports:
      # P2P port
      - "11333:11333"

  litecoin.testnet:
    << : *defaults
    container_name: litecoin.testnet
    image: litecoin.testnet
    build:
      context: ./litecoin
      args:
        - LITECOIN_VERSION
    environment:
      - EXTERNAL_IP
      - LITECOIN_RPC_AUTH
      - LITECOIN_RPC_USER
      - LITECOIN_RPC_PASSWORD
    volumes:
      - /connector/litecoin.testnet:/root/.litecoin
    ports:
      # P2P port
      - "12333:12333"